### Plugin Name ###
name: UpgradeFurnace

### Build Version ###
version: '2.1.0'

### Main Class ###
main: at.lowdfx.upgradeFurnace.UpgradeFurnace

### PaperAPI Version ###
api-version: '1.21.11'

dependencies:
  server:
    mcMMO:
      load: BEFORE
      required: false
      join-classpath: true

### Authors ###
authors:
  - LowdFX
  - Menkhaz
